language: java

dist: jammy

jdk:
  - openjdk25

addons:
  apt:
    update: true
    packages:
      - bc
      - parallel

before_install:
  - sudo apt-get update
  - sudo apt-get install -y bc parallel

script:
  - make verify || true
